# IMPORTANT: The version must match the version of docker-compose.yml
---
version: '3'

# All additional integrations should be added following this format only.

services:
  boxjs:
    image: intelowlproject/intelowl_boxjs:${INTELOWL_TAG_VERSION}
    container_name: intelowl_boxjs
    restart: unless-stopped
    expose:
      - "4003"
    env_file:
      - env_file_integrations
    volumes:
      - generic_logs:/var/log/intel_owl
    depends_on:
      - uwsgi
