# IMPORTANT: The version must match the version of docker-compose.yml
---
version: '3'

# All additional integrations should be added following this format only.

services:
  peframe:
    build:
      context: ./integrations/peframe
      dockerfile: Dockerfile
    container_name: intelowl_peframe
    restart: unless-stopped
    expose:
      - "4000"
    env_file:
      - env_file_integrations
    volumes:
      - generic_logs:/var/log/intel_owl
    depends_on:
      - uwsgi
