repos:
  - repo: https://github.com/psf/black
    rev: 22.3.0
    hooks:
      - id: black
  - repo: https://github.com/pycqa/flake8
    rev: 4.0.1
    hooks:
      - id: flake8
  - repo: https://github.com/pycqa/isort
    rev: 5.10.1
    hooks:
      - id: isort
        args:
          [
            "--profile",
            "black",
            "--filter-files",
            "--skip",
            "venv",
            "--skip",
            "configuration/ldap_config.py",
          ]
  - repo: https://github.com/pre-commit/mirrors-eslint
    rev: v8.16.0
    hooks:
      - id: eslint
        additional_dependencies:
          - eslint@8.16.0
          - eslint-config-airbnb@19.0.4
          - eslint-config-prettier@8.5.0
          - eslint-plugin-import@2.26.0
          - eslint-plugin-jsx-a11y@6.5.1
          - eslint-plugin-react@7.30.0
          - eslint-plugin-react-hooks@4.5.0
        args: ["--fix"]
        files: frontend/src/
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v2.6.2
    hooks:
      - id: prettier
        files: frontend/src/
  - repo: https://github.com/awebdeveloper/pre-commit-stylelint
    rev: 0.0.2
    hooks:
      - id: stylelint
        additional_dependencies:
          - stylelint@14.8.5
          - stylelint-config-prettier@9.0.3
          - stylelint-config-standard-scss@4.0.0
        args: ["--fix"]
        files: frontend/src/styles/.*(css|scss)$
