version: '3'

services:
  traefik:
    image: "traefik:v2.2"
    container_name: "traefik"
    command:
      #- "--log.level=DEBUG"
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.websecure.address=:443"
      - "--certificatesresolvers.myresolver.acme.httpchallenge=true"
      - "--certificatesresolvers.myresolver.acme.httpchallenge.entrypoint=web"
      #- "--certificatesresolvers.myresolver.acme.caserver=https://acme-staging-v02.api.letsencrypt.org/directory"
      - "--certificatesresolvers.myresolver.acme.email=postmaster@example.com"
      - "--certificatesresolvers.myresolver.acme.storage=/letsencrypt/acme.json"
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - "./letsencrypt:/letsencrypt"
      - "/var/run/docker.sock:/var/run/docker.sock:ro"

  postgres:
    image: library/postgres:12-alpine
    container_name: intel_owl_postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./env_file_postgres

  uwsgi:
    image: intelowlproject/intelowl:${INTELOWL_TAG_VERSION}
    container_name: intel_owl_uwsgi
    volumes:
      - ./configuration/intel_owl.ini:/etc/uwsgi/sites/intel_owl.ini
      - ./configuration/analyzer_config.json:/opt/deploy/configuration/analyzer_config.json
      - ./configuration/ldap_config.py:/opt/deploy/configuration/ldap_config.py
      - generic_logs:/var/log/intel_owl
      - static_content:/opt/deploy/intel_owl/static
      - shared_files:/opt/deploy/files_required
    entrypoint:
      - ./docker_entrypoint.sh
    expose:
      - "8001"
    env_file:
      - env_file_app
    depends_on:
      - postgres

  nginx:
    build:
      context: .
      dockerfile: ./Dockerfile_nginx
    container_name: intel_owl_nginx
    restart: unless-stopped
    hostname: nginx
    volumes:
      - ./configuration/intel_owl_nginx_http:/etc/nginx/conf.d/default.conf
      - nginx_logs:/var/log/nginx
      - static_content:/var/www/static
    depends_on:
      - uwsgi
      - traefik
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.nginx.rule=Host(`example.com`)"
      - "traefik.http.routers.nginx.entrypoints=websecure"
      - "traefik.http.routers.nginx.tls.certresolver=myresolver"

  rabbitmq:
    image: library/rabbitmq:3.8-alpine
    container_name: intel_owl_rabbitmq

  celery_beat:
    image: intelowlproject/intelowl:${INTELOWL_TAG_VERSION}
    container_name: intel_owl_celery_beat
    restart: unless-stopped
    command: /usr/local/bin/celery -A intel_owl.celery beat --uid www-data --gid www-data --pidfile=/tmp/celerybeat.pid --schedule=/tmp/celerybeat-schedule
    volumes:
      - ./configuration/analyzer_config.json:/opt/deploy/configuration/analyzer_config.json
      - generic_logs:/var/log/intel_owl
      - shared_files:/opt/deploy/files_required
    env_file:
      - env_file_app
    depends_on:
      - rabbitmq
      - postgres

  celery_worker:
    image: intelowlproject/intelowl:${INTELOWL_TAG_VERSION}
    container_name: intel_owl_celery_worker
    restart: unless-stopped
    stop_grace_period: 3m
    command: /usr/local/bin/celery -A intel_owl.celery worker --uid www-data --gid www-data --pidfile="/tmp/%n.pid"
    volumes:
      - ./configuration/analyzer_config.json:/opt/deploy/configuration/analyzer_config.json
      - generic_logs:/var/log/intel_owl
      - shared_files:/opt/deploy/files_required
    env_file:
      - env_file_app
    depends_on:
      - rabbitmq
      - postgres

volumes:
  postgres_data:
  nginx_logs:
  generic_logs:
  static_content:
  shared_files:

