version: '3'

services:
  postgres:
    image: library/postgres:12.1-alpine
    container_name: intel_owl_postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./env_file_postgres_template

  uwsgi:
    build: .
    container_name: intel_owl_uwsgi
    volumes:
      - ./configuration/intel_owl.ini:/etc/uwsgi/sites/intel_owl.ini
      - ./configuration/analyzer_config.json:/opt/deploy/configuration/analyzer_config.json
      - generic_logs:/var/log/intel_owl
      - static_content:/opt/deploy/intel_owl/static
      - shared_files:/opt/deploy/files_required
    entrypoint:
      - ./docker_entrypoint.sh
    expose:
      - "8001"
    env_file:
      - env_file_app_travis
    depends_on:
      - postgres

  nginx:
    image: library/nginx:1.16.1-alpine
    container_name: intel_owl_nginx
    restart: unless-stopped
    hostname: nginx
    volumes:
      - ./configuration/intel_owl_nginx_http:/etc/nginx/conf.d/default.conf
      - nginx_logs:/var/log/nginx
      - static_content:/var/www/static
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - uwsgi

  rabbitmq:
    image: library/rabbitmq:3.8.2-alpine
    container_name: intel_owl_rabbitmq

  celery_beat:
    build: .
    container_name: intel_owl_celery_beat
    restart: unless-stopped
<<<<<<< HEAD
    command: /usr/local/bin/celery -A intel_owl.celery beat --uid www-data --gid www-data --pidfile=/tmp/celerybeat.pid --schedule=/tmp/celerybeat-schedule
=======
    command: /usr/local/bin/celery -A intel_owl.celery beat --uid www-data --gid www-data -l info -f "/var/log/intel_owl/celery/beat.log" --pidfile=/tmp/celerybeat.pid --schedule=/tmp/celerybeat-schedule
>>>>>>> Added ONYPHE API integration
    volumes:
      - ./configuration/analyzer_config.json:/opt/deploy/configuration/analyzer_config.json
      - generic_logs:/var/log/intel_owl
      - shared_files:/opt/deploy/files_required
    env_file:
      - env_file_app_travis
    depends_on:
      - rabbitmq
      - postgres

  celery_worker:
    build: .
    container_name: intel_owl_celery_worker
    restart: unless-stopped
    stop_grace_period: 3m
<<<<<<< HEAD
    command: /usr/local/bin/celery -A intel_owl.celery worker --uid www-data --gid www-data --pidfile="/tmp/%n.pid" --time-limit=1000
=======
    command: /usr/local/bin/celery -A intel_owl.celery worker --uid www-data --gid www-data -l info --logfile="/var/log/intel_owl/celery/%n.log" --pidfile="/tmp/%n.pid" --time-limit=1000
>>>>>>> Added ONYPHE API integration
    volumes:
      - ./configuration/analyzer_config.json:/opt/deploy/configuration/analyzer_config.json
      - generic_logs:/var/log/intel_owl
      - shared_files:/opt/deploy/files_required
    env_file:
      - env_file_app_travis
    depends_on:
      - rabbitmq
      - postgres

volumes:
  postgres_data:
  nginx_logs:
  generic_logs:
  static_content:
  shared_files:

