# IMPORTANT: The version must match the version of docker-compose.yml
---
version: "3.8"

# All additional integrations should be added following this format only.

services:
  static_analyzers:
    image: intelowlproject/intelowl_static_analyzers:${INTELOWL_TAG_VERSION}
    container_name: intelowl_static_analyzers
    restart: unless-stopped
    expose:
      - "4002"
    env_file:
      - env_file_integrations
    volumes:
      - generic_logs:/var/log/intel_owl
      - clam:/var/lib/clamav
      - ../integrations/static_analyzers/clamav_config/clamd.conf:/etc/clamav/clamd.conf
      - ../integrations/static_analyzers/clamav_config/freshclam.conf:/etc/clamav/freshclam.conf
    depends_on:
      - uwsgi

volumes:
  clam:
