version: '3.8'

services:
  postgres:
    image: library/postgres:12-alpine
    container_name: intelowl_postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./env_file_postgres

  uwsgi:
    image: intelowlproject/intelowl:${INTELOWL_TAG_VERSION}
    container_name: intelowl_uwsgi
    volumes:
      - ../configuration/intel_owl.ini:/etc/uwsgi/sites/intel_owl.ini # uwsgi configuration file
      - ../configuration:/opt/deploy/intel_owl/configuration
      - generic_logs:/var/log/intel_owl
      - static_content:/opt/deploy/intel_owl/static
      - shared_files:/opt/deploy/files_required
    entrypoint:
      - ./docker/entrypoints/uwsgi.sh
    expose:
      - "8001"
    env_file:
      - env_file_app
      - .env
    depends_on:
      - postgres

  nginx:
    image: intelowlproject/intelowl_nginx:${INTELOWL_TAG_VERSION}
    container_name: intelowl_nginx
    restart: unless-stopped
    hostname: nginx
    volumes:
      - ../configuration/nginx/errors.conf:/etc/nginx/errors.conf
      - ../configuration/nginx/http.conf:/etc/nginx/conf.d/default.conf
      - ../configuration/nginx/locations.conf:/etc/nginx/locations.conf
      - nginx_logs:/var/log/nginx
      - static_content:/var/www/static
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - uwsgi

  rabbitmq:
    image: library/rabbitmq:3.9-alpine
    container_name: intelowl_rabbitmq
    logging:
      driver: none

  celery_beat:
    image: intelowlproject/intelowl:${INTELOWL_TAG_VERSION}
    container_name: intelowl_celery_beat
    restart: unless-stopped
    volumes:
      - ../configuration:/opt/deploy/intel_owl/configuration
      - generic_logs:/var/log/intel_owl
      - shared_files:/opt/deploy/files_required
    entrypoint:
      - ./docker/entrypoints/celery_beat.sh
    env_file:
      - env_file_app
    depends_on:
      - rabbitmq
      - postgres
      - uwsgi

  celery_worker_default:
    image: intelowlproject/intelowl:${INTELOWL_TAG_VERSION}
    container_name: intelowl_celery_worker_default
    restart: unless-stopped
    stop_grace_period: 3m
    volumes:
      - ../configuration:/opt/deploy/intel_owl/configuration
      - generic_logs:/var/log/intel_owl
      - shared_files:/opt/deploy/files_required
    entrypoint:
      - ./docker/entrypoints/celery_default.sh
    logging:
      driver: "json-file"
      options:
        max-file: "5"
        max-size: "10m"
    env_file:
      - env_file_app
    depends_on:
      - rabbitmq
      - postgres
      - uwsgi


volumes:
  postgres_data:
  nginx_logs:
  generic_logs:
  static_content:
  shared_files:
