version: "3.8"

services:
  uwsgi:
    environment:
      - BROKER_URL_API=http://guest:guest@rabbitmq:15672/api/

  rabbitmq:
    image: library/rabbitmq:3.11-management-alpine
    hostname: rabbitmq
    container_name: intelowl_rabbitmq
    logging:
      driver: none
    expose:
      - "15672"

  flower:
    image: intelowlproject/intelowl:${REACT_APP_INTELOWL_VERSION}
    container_name: intelowl_flower
    hostname: flower
    restart: unless-stopped
    stop_grace_period: 3m
    volumes:
      - generic_logs:/var/log/intel_owl
      - shared_htpasswd:/opt/deploy/shared_htpasswd
    expose:
      - "5555"
    depends_on:
      - rabbitmq
      - uwsgi
    entrypoint:
      - ./docker/entrypoints/flower.sh
    env_file:
      - env_file_app
    healthcheck:
      disable: true

  nginx:
    volumes:
      - shared_htpasswd:/etc/nginx/shared
      - ../configuration/nginx/flower_http.conf:/etc/nginx/conf.d/flower.conf
    ports:
      - "5555:5555"
    depends_on:
      - rabbitmq

volumes:
  shared_htpasswd: