version: '3.8'

x-no-healthcheck: &no-healthcheck
  healthcheck:
    disable: true

services:
  uwsgi:
    environment:
      - CELERY_QUEUES=default,local,long

  celery_worker_local:
    image: intelowlproject/intelowl:${REACT_APP_INTELOWL_VERSION}
    container_name: intelowl_celery_worker_local
    restart: unless-stopped
    hostname: celery_worker_local
    stop_grace_period: 3m
    volumes:
      - ../configuration:/opt/deploy/intel_owl/configuration
      - generic_logs:/var/log/intel_owl
      - shared_files:/opt/deploy/files_required
    entrypoint:
      - ./docker/entrypoints/celery_local.sh
    env_file:
      - env_file_app
    depends_on:
      uwsgi:
        condition: service_healthy
    <<: *no-healthcheck

  celery_worker_long:
    image: intelowlproject/intelowl:${REACT_APP_INTELOWL_VERSION}
    container_name: intelowl_celery_worker_long
    hostname: celery_worker_long
    restart: unless-stopped
    stop_grace_period: 3m
    volumes:
      - ../configuration:/opt/deploy/intel_owl/configuration
      - generic_logs:/var/log/intel_owl
      - shared_files:/opt/deploy/files_required
    entrypoint:
      - ./docker/entrypoints/celery_long.sh
    env_file:
      - env_file_app
    depends_on:
      uwsgi:
        condition: service_healthy
    <<: *no-healthcheck

  celery_worker_ingestor:
    image: intelowlproject/intelowl:${REACT_APP_INTELOWL_VERSION}
    container_name: intelowl_celery_worker_ingestor
    hostname: celery_worker_ingestor
    restart: unless-stopped
    stop_grace_period: 3m
    volumes:
      - ../configuration:/opt/deploy/intel_owl/configuration
      - generic_logs:/var/log/intel_owl
      - shared_files:/opt/deploy/files_required
    entrypoint:
      - ./docker/entrypoints/celery_ingestor.sh
    env_file:
      - env_file_app
    depends_on:
      uwsgi:
        condition: service_healthy
    <<: *no-healthcheck
