version: '3.8'

services:
  celery_worker_local:
    image: intelowlproject/intelowl:test
    volumes:
      - ../:/opt/deploy/intel_owl

  celery_worker_long:
    image: intelowlproject/intelowl:test
    volumes:
      - ../:/opt/deploy/intel_owl

  celery_worker_ingestor:
    image: intelowlproject/intelowl:test
    volumes:
      - ../:/opt/deploy/intel_owl