version: "3.8"

services:
  uwsgi:
    build:
      context: ..
      dockerfile: docker/Dockerfile
      args:
        REPO_DOWNLOADER_ENABLED: ${REPO_DOWNLOADER_ENABLED}
        WATCHMAN: true
        PYCTI_VERSION: ${PYCTI_VERSION:-5.10.0}
    image: intelowlproject/intelowl:test
    volumes:
      - ../:/opt/deploy/intel_owl
    environment:
      - DEBUG=True
      - DJANGO_TEST_SERVER=True
      - DJANGO_WATCHMAN_TIMEOUT=60
      - WATCHMAN=True

  daphne:
    image: intelowlproject/intelowl:test
    volumes:
      - ../:/opt/deploy/intel_owl

  nginx:
    build:
      context: ..
      dockerfile: docker/Dockerfile_nginx
    image: intelowlproject/intelowl_nginx:test
    volumes:
      - ../configuration/nginx/django_server.conf:/etc/nginx/conf.d/default.conf

  celery_beat:
    image: intelowlproject/intelowl:test
    volumes:
      - ../:/opt/deploy/intel_owl
    environment:
      - DEBUG=True
      - DJANGO_TEST_SERVER=True
      - DJANGO_WATCHMAN_TIMEOUT=60
      - WATCHMAN=True

  celery_worker_default:
    image: intelowlproject/intelowl:test
    volumes:
      - ../:/opt/deploy/intel_owl
    environment:
      - DEBUG=True
      - DJANGO_TEST_SERVER=True
      - DJANGO_WATCHMAN_TIMEOUT=60
      - WATCHMAN=True