version: "3.8"

services:
  uwsgi:
    build:
      context: ..
      dockerfile: docker/Dockerfile
      args:
        REPO_DOWNLOADER_ENABLED: ${REPO_DOWNLOADER_ENABLED}
    image: intelowlproject/intelowl:test
    volumes:
      - ../:/opt/deploy/intel_owl
    environment:
      - DEBUG=True

  nginx:
    build:
      context: ..
      dockerfile: docker/Dockerfile_nginx

  celery_beat:
    image: intelowlproject/intelowl:test

  celery_worker_default:
    image: intelowlproject/intelowl:test
